+UseOS = "el9"
+JobCategory = "short"
executable = main.sh

# Experiment parameters
DATASET = GW
SUBSYSTEMS = IMC
BATCH = 256
EPOCHS = 400
SLIDE_WIN = 100
SLIDE_STRIDE = 5
DIM = 128
TOPK = 15
OUT_LAYER_NUM = 1
OUT_LAYER_INTER_DIM = 128
VAL_RATIO = 0.2
TEST_RATIO = 0.1
DECAY = 1e-5
LR = 1e-4
SEED = 100
REPORT = val

# Automatic experiment name
EXPNAME =  $(SUBSYSTEMS)_$(SLIDE_WIN)s_k$(TOPK)

# Python arguments
arguments = \
    -dataset $(DATASET) \
    -subsystems $(SUBSYSTEMS) \
    -batch $(BATCH) \
    -epoch $(EPOCHS) \
    -slide_win $(SLIDE_WIN) \
    -slide_stride $(SLIDE_STRIDE) \
    -dim $(DIM) \
    -topk $(TOPK) \
    -out_layer_num $(OUT_LAYER_NUM) \
    -out_layer_inter_dim $(OUT_LAYER_INTER_DIM) \
    -val_ratio $(VAL_RATIO) \
    -test_ratio $(TEST_RATIO) \
    -learning_rate $(LR) \
    -decay $(DECAY) \
    -random_seed $(SEED) \
    -report $(REPORT) \
    -comment $(EXPNAME) \
    -save_path_pattern $(DATASET)

# Output files
output = condor_files/output/$(EXPNAME).out
error  = condor_files/error/$(EXPNAME).err
log    = condor_files/log/$(EXPNAME).log


# Resources
request_memory = 50 Gb
request_disk   = 2 Gb
request_gpus   = 1
request_cpus   = 2

queue
